# Generated by Django 2.1 on 2018-08-28 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='desctrption',
            new_name='description',
        ),
    ]
